export const GREENHOUSE_BOARDS = [
  { id: "airbnb", label: "Airbnb" },
  { id: "andurilindustries", label: "Anduril" },
  { id: "benchling", label: "Benchling" },
  { id: "brex", label: "Brex" },
  { id: "checkr", label: "Checkr" },
  { id: "coinbase", label: "Coinbase" },
  { id: "cruise", label: "Cruise" },
  { id: "databricks", label: "Databricks" },
  { id: "discord", label: "Discord" },
  { id: "figma", label: "Figma" },
  { id: "fivetran", label: "Fivetran" },
  { id: "flexport", label: "Flexport" },
  { id: "gusto", label: "Gusto" },
  { id: "instacart", label: "Instacart" },
  { id: "intercom", label: "Intercom" },
  { id: "ironclad", label: "Ironclad" },
  { id: "lyft", label: "Lyft" },
  { id: "miro", label: "Miro" },
  { id: "mongodb", label: "MongoDB" },
  { id: "mux", label: "Mux" },
  { id: "notion", label: "Notion" },
  { id: "nuro", label: "Nuro" },
  { id: "patreon", label: "Patreon" },
  { id: "pinterest", label: "Pinterest" },
  { id: "ramp", label: "Ramp" },
  { id: "reddit", label: "Reddit" },
  { id: "retool", label: "Retool" },
  { id: "rubrik", label: "Rubrik" },
  { id: "samsara", label: "Samsara" },
  { id: "scaleai", label: "Scale AI" },
  { id: "sentry", label: "Sentry" },
  { id: "stripe", label: "Stripe" },
  { id: "toast", label: "Toast" },
  { id: "twitch", label: "Twitch" },
  { id: "verkada", label: "Verkada" },
  { id: "waymo", label: "Waymo" },
  { id: "yelp", label: "Yelp" },
  { id: "zapier", label: "Zapier" },
] as const;

export const SMART_RECRUITERS_COMPANIES = [
  { id: "Visa", label: "Visa" },
  { id: "Sportradar", label: "Sportradar" },
  { id: "Wise", label: "Wise" },
  { id: "BoschGroup", label: "Bosch" },
  { id: "Canva", label: "Canva" },
  { id: "DeliveryHero", label: "Delivery Hero" },
] as const;

export const ARBEITNOW_PAGE_COUNT = 12;
export const THE_MUSE_PAGE_COUNT = 10;
